version: '3.7'

services:
  rust:
    image: rust:latest
    container_name: rust_dev
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    environment:
      - USER=GUEST
      - CARGO_BUILD_TARGET_DIR=/app/target